#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PetGo.Resource", IsApplication=true)]

namespace PetGo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int android = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int announcement = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bath_happy = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bath_unhappy = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int border = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int drink_happy = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int drink_unhappy = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int eat_happy = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int eat_unhappy = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int idle_happy = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int idle_unhappy = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int med_happy = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int med_unhappy = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int park_happy = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int park_unhappy = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int previewImage = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sick = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int sleep = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int buttonBath = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int buttonDrink = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int buttonFeed = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int buttonGoOut = 2131099652;
			
			// aapt resource value: 0x7f060008
			public const int buttonMed = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int buttonSleep = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int room = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int widgetBackground = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Widget = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int appwidgetprovider = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
